
{{- if .Values.servicios.gateway.enabled }}
{{- include "barberia.componente" (dict
      "nombre" "servicio-gateway"
      "etiqueta" "gateway"
      "cfg" .Values.servicios.gateway
      "replicas" .Values.replicaCount
      "tag" .Values.imageTag) }}
{{- end }}
