-- Equipo de barberos, tomado del mockup de referencia.
--
-- Se ejecuta en CADA arranque (spring.sql.init.mode=always), por eso todo va
-- condicionado a que la tabla este VACIA: si el administrador da de baja a un
-- barbero, el arranque siguiente no debe resucitarlo.
--
-- Los ids van explicitos (1, 2, 3) porque las tablas hijas barbero_slots y
-- barbero_galeria necesitan referenciarlos, y porque las cuentas de acceso de
-- barberia_auth guardan ese mismo id en usuarios.barbero_id. La columna es
-- GENERATED BY DEFAULT AS IDENTITY, que si admite ids explicitos (ALWAYS no).

INSERT INTO barberos (id, nombre, nombre_corto, cargo, especialidad, anios_experiencia,
                      cortes, color, instagram, facebook, foto_url, activo)
SELECT * FROM (VALUES
    (1, 'Marcos Villegas', 'MARCOS V.', 'Master Barber', 'Fades & Degradados', 12,
     '8.4K', '#39ff14', '@marcosbarber', 'fb.com/marcosbarber',
     'https://images.unsplash.com/photo-1553521041-d168abd31de3?w=500&h=600&fit=crop&auto=format', true),
    (2, 'Santiago Ríos', 'SANTIAGO R.', 'Senior Barber', 'Clásico & Barba', 8,
     '5.2K', '#ff3cac', '@santiagobarber', 'fb.com/santiagobarber',
     'https://images.unsplash.com/photo-1599351431202-1e0f0137899a?w=500&h=600&fit=crop&auto=format', true),
    (3, 'Diego Castillo', 'DIEGO C.', 'Barber Artist', 'Diseños & Arte', 5,
     '2.9K', '#00d4ff', '@diegobarber', 'fb.com/diegobarber',
     'https://images.unsplash.com/photo-1543132220-3ec99c6094dc?w=500&h=600&fit=crop&auto=format', true)
) AS v(id, nombre, nombre_corto, cargo, especialidad, anios_experiencia,
       cortes, color, instagram, facebook, foto_url, activo)
WHERE NOT EXISTS (SELECT 1 FROM barberos);

-- Franjas horarias que ofrece cada barbero.
INSERT INTO barbero_slots (barbero_id, slot)
SELECT * FROM (VALUES
    (1, '10:00'), (1, '11:30'), (1, '14:00'), (1, '16:30'),
    (2, '09:00'), (2, '13:00'), (2, '15:30'), (2, '17:00'),
    (3, '11:00'), (3, '12:30'), (3, '14:30'), (3, '18:00')
) AS v(barbero_id, slot)
WHERE NOT EXISTS (SELECT 1 FROM barbero_slots);

-- Galeria de trabajos de cada barbero.
INSERT INTO barbero_galeria (barbero_id, url)
SELECT * FROM (VALUES
    (1, 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=400&h=400&fit=crop&auto=format'),
    (1, 'https://images.unsplash.com/photo-1517832606299-7ae9b720a186?w=400&h=400&fit=crop&auto=format'),
    (1, 'https://images.unsplash.com/photo-1635273051937-a0ddef9573b6?w=400&h=400&fit=crop&auto=format'),
    (2, 'https://images.unsplash.com/photo-1647140655214-e4a2d914971f?w=400&h=400&fit=crop&auto=format'),
    (2, 'https://images.unsplash.com/photo-1621645582931-d1d3e6564943?w=400&h=400&fit=crop&auto=format'),
    (2, 'https://images.unsplash.com/photo-1593702275687-f8b402bf1fb5?w=400&h=400&fit=crop&auto=format'),
    (3, 'https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=400&h=400&fit=crop&auto=format'),
    (3, 'https://images.unsplash.com/photo-1553521041-d168abd31de3?w=400&h=400&fit=crop&auto=format'),
    (3, 'https://images.unsplash.com/photo-1543132220-3ec99c6094dc?w=400&h=400&fit=crop&auto=format')
) AS v(barbero_id, url)
WHERE NOT EXISTS (SELECT 1 FROM barbero_galeria);

-- Al insertar ids a mano la secuencia se queda en 1, y el primer barbero que
-- diera de alta el administrador chocaria con la clave primaria. Esto la deja
-- apuntando al maximo actual.
SELECT setval(pg_get_serial_sequence('barberos', 'id'),
              COALESCE((SELECT MAX(id) FROM barberos), 1));
