events {
    worker_connections 1024;
}

http {
    upstream servicios {
        server localhost:8081;
    }

    upstream barberos {
        server localhost:8082;
    }

    upstream citas {
        server localhost:8083;
    }

    upstream auth {
        server localhost:8084;
    }

    server {
        listen 8080;

        location /api/servicios/ {
            proxy_pass http://servicios;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/barberos/ {
            proxy_pass http://barberos;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/citas/ {
            proxy_pass http://citas;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /auth/ {
            proxy_pass http://auth;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            return 200 'API Gateway funcionando correctamente';
            add_header Content-Type text/plain;
        }
    }
}