-- =============================================================================
-- RESPALDO MANUAL del esquema. NO hace falta ejecutarlo en condiciones normales:
-- Hibernate crea estas tablas al arrancar (ddl-auto: update) y los data.sql de
-- cada microservicio insertan los datos de ejemplo.
--
-- Usalo cuando quieras el esquema sin levantar los microservicios, o para
-- inspeccionar/recrear a mano desde pgAdmin.
--
-- OJO: este archivo toca CUATRO bases distintas. Ejecutalo asi, que si procesa
-- los \connect:
--
--   docker exec -i barberia-postgres psql -U postgres -f - < sql/crear-tablas-y-datos.sql
--
-- Desde pgAdmin: abre cada bloque por separado, conectado a la base que toca.
--
-- El DDL replica lo que genera Hibernate (identity, varchar(255), timestamp(6));
-- si lo cambias, JPA intentara alterarlo en el proximo arranque.
-- =============================================================================


-- =============================================================================
-- 1. barberia_servicios
-- =============================================================================
\connect barberia_servicios

CREATE TABLE IF NOT EXISTS servicios (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           varchar(255)     NOT NULL,
    descripcion      varchar(255),
    precio           double precision NOT NULL,
    duracion_minutos integer,
    tag              varchar(255)   -- BESTSELLER, TRENDING, PREMIUM, RITUAL o NULL
);

INSERT INTO servicios (nombre, descripcion, precio, duracion_minutos, tag)
SELECT * FROM (VALUES
    ('Corte Clásico',   'Tijera y máquina, lavado y peinado final',  25.0, 45, 'BESTSELLER'),
    ('Fade & Líneas',   'Degradado a piel con perfilado de líneas',  35.0, 60, 'TRENDING'),
    ('Barba Completa',  'Perfilado, toalla caliente y aceites',      20.0, 30, NULL),
    ('Corte + Barba',   'El combo completo: corte, barba y ritual',  50.0, 90, 'PREMIUM'),
    ('Tratamiento',     'Hidratación capilar y masaje',              30.0, 45, NULL),
    ('Afeitado Navaja', 'Afeitado tradicional a navaja con toalla',  28.0, 40, 'RITUAL')
) AS v(nombre, descripcion, precio, duracion_minutos, tag)
WHERE NOT EXISTS (SELECT 1 FROM servicios);


-- =============================================================================
-- 2. barberia_barberos
-- =============================================================================
\connect barberia_barberos

CREATE TABLE IF NOT EXISTS barberos (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre            varchar(255) NOT NULL,
    nombre_corto      varchar(255),
    cargo             varchar(255),
    especialidad      varchar(255),
    anios_experiencia integer,
    cortes            varchar(255),   -- texto: se muestra abreviado ("8.4K")
    color             varchar(255),   -- acento hexadecimal en la UI
    instagram         varchar(255),
    facebook          varchar(255),
    foto_url          varchar(255),
    activo            boolean NOT NULL DEFAULT true
);

-- Tablas hijas de las colecciones (@ElementCollection). Se prefieren a un CSV en
-- una columna porque asi se pueden consultar y ordenar desde SQL.
CREATE TABLE IF NOT EXISTS barbero_slots (
    barbero_id bigint NOT NULL REFERENCES barberos (id),
    slot       varchar(255)
);

CREATE TABLE IF NOT EXISTS barbero_galeria (
    barbero_id bigint NOT NULL REFERENCES barberos (id),
    url        varchar(255)
);

-- Ids explicitos: las cuentas de barberia_auth guardan estos mismos valores en
-- usuarios.barbero_id, y las tablas hijas los referencian.
INSERT INTO barberos (id, nombre, nombre_corto, cargo, especialidad, anios_experiencia,
                      cortes, color, instagram, facebook, foto_url, activo)
SELECT * FROM (VALUES
    (1, 'Marcos Villegas', 'MARCOS V.', 'Master Barber', 'Fades & Degradados', 12,
     '8.4K', '#39ff14', '@marcosbarber', 'fb.com/marcosbarber',
     'https://images.unsplash.com/photo-1553521041-d168abd31de3?w=500&h=600&fit=crop&auto=format', true),
    (2, 'Santiago Ríos', 'SANTIAGO R.', 'Senior Barber', 'Clásico & Barba', 8,
     '5.2K', '#ff3cac', '@santiagobarber', 'fb.com/santiagobarber',
     'https://images.unsplash.com/photo-1599351431202-1e0f0137899a?w=500&h=600&fit=crop&auto=format', true),
    (3, 'Diego Castillo', 'DIEGO C.', 'Barber Artist', 'Diseños & Arte', 5,
     '2.9K', '#00d4ff', '@diegobarber', 'fb.com/diegobarber',
     'https://images.unsplash.com/photo-1543132220-3ec99c6094dc?w=500&h=600&fit=crop&auto=format', true)
) AS v(id, nombre, nombre_corto, cargo, especialidad, anios_experiencia,
       cortes, color, instagram, facebook, foto_url, activo)
WHERE NOT EXISTS (SELECT 1 FROM barberos);

INSERT INTO barbero_slots (barbero_id, slot)
SELECT * FROM (VALUES
    (1, '10:00'), (1, '11:30'), (1, '14:00'), (1, '16:30'),
    (2, '09:00'), (2, '13:00'), (2, '15:30'), (2, '17:00'),
    (3, '11:00'), (3, '12:30'), (3, '14:30'), (3, '18:00')
) AS v(barbero_id, slot)
WHERE NOT EXISTS (SELECT 1 FROM barbero_slots);

-- Al insertar ids a mano la secuencia se queda en 1 y el siguiente alta chocaria
-- con la clave primaria. Esto la deja apuntando al maximo actual.
SELECT setval(pg_get_serial_sequence('barberos', 'id'),
              COALESCE((SELECT MAX(id) FROM barberos), 1));


-- =============================================================================
-- 3. barberia_citas  (arranca vacia: se llena desde el formulario de reserva)
-- =============================================================================
\connect barberia_citas

CREATE TABLE IF NOT EXISTS citas (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_nombre   varchar(255) NOT NULL,
    cliente_telefono varchar(255) NOT NULL,
    servicio_id      bigint       NOT NULL,
    barbero_id       bigint,        -- columna por la que se filtra "mi agenda"
    barbero          varchar(255),  -- nombre copiado, solo para mostrar
    fecha_hora       timestamp(6) NOT NULL,
    notas            varchar(500),
    estado           varchar(255)   -- PENDIENTE, CONFIRMADA, COMPLETADA, CANCELADA
);

-- servicio_id y barbero_id NO tienen clave foranea a proposito: viven en OTRAS
-- bases de datos (barberia_servicios y barberia_barberos). Es el precio del
-- patron database-per-service; la integridad la valida la aplicacion.


-- =============================================================================
-- 4. barberia_auth
-- =============================================================================
\connect barberia_auth

CREATE TABLE IF NOT EXISTS usuarios (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   varchar(255) NOT NULL UNIQUE,
    password   varchar(255) NOT NULL,  -- hash BCrypt ($2a$10$...)
    rol        varchar(255),           -- ADMIN o BARBERO
    nombre     varchar(255),
    barbero_id bigint                  -- solo en cuentas BARBERO
);

-- Las contrasenas van aqui en texto plano porque SQL no puede generar un hash
-- BCrypt: el algoritmo vive en la aplicacion. No es un descuido, es el mecanismo:
-- al arrancar, PasswordMigrationRunner detecta las que no empiezan por '$2' y las
-- convierte a BCrypt. En la tabla acaban cifradas igualmente.
INSERT INTO usuarios (username, password, rol, nombre, barbero_id)
SELECT * FROM (VALUES
    ('admin',    'admin123',    'ADMIN',   'Administrador',   CAST(NULL AS BIGINT)),
    ('marcos',   'marcos123',   'BARBERO', 'Marcos Villegas', CAST(1 AS BIGINT)),
    ('santiago', 'santiago123', 'BARBERO', 'Santiago Ríos',   CAST(2 AS BIGINT)),
    ('diego',    'diego123',    'BARBERO', 'Diego Castillo',  CAST(3 AS BIGINT))
) AS v(username, password, rol, nombre, barbero_id)
WHERE NOT EXISTS (SELECT 1 FROM usuarios);
